// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gol.proto

package gol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Methods int32

const (
	Methods_post  Methods = 0
	Methods_get   Methods = 1
	Methods_put   Methods = 2
	Methods_patch Methods = 3
)

var Methods_name = map[int32]string{
	0: "post",
	1: "get",
	2: "put",
	3: "patch",
}

var Methods_value = map[string]int32{
	"post":  0,
	"get":   1,
	"put":   2,
	"patch": 3,
}

func (x Methods) String() string {
	return proto.EnumName(Methods_name, int32(x))
}

func (Methods) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d7052d12ff7cf86b, []int{0}
}

type SequenceType int32

const (
	SequenceType_parallel SequenceType = 0
	SequenceType_sync     SequenceType = 1
)

var SequenceType_name = map[int32]string{
	0: "parallel",
	1: "sync",
}

var SequenceType_value = map[string]int32{
	"parallel": 0,
	"sync":     1,
}

func (x SequenceType) String() string {
	return proto.EnumName(SequenceType_name, int32(x))
}

func (SequenceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d7052d12ff7cf86b, []int{1}
}

type ExecuteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7052d12ff7cf86b, []int{0}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

type ExecuteRequest struct {
	Sequence             []*Sequence `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7052d12ff7cf86b, []int{1}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetSequence() []*Sequence {
	if m != nil {
		return m.Sequence
	}
	return nil
}

type Sequence struct {
	Type                 SequenceType `protobuf:"varint,1,opt,name=type,proto3,enum=gol.SequenceType" json:"type,omitempty"`
	Jobs                 []*Job       `protobuf:"bytes,2,rep,name=Jobs,proto3" json:"Jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Sequence) Reset()         { *m = Sequence{} }
func (m *Sequence) String() string { return proto.CompactTextString(m) }
func (*Sequence) ProtoMessage()    {}
func (*Sequence) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7052d12ff7cf86b, []int{2}
}

func (m *Sequence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sequence.Unmarshal(m, b)
}
func (m *Sequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sequence.Marshal(b, m, deterministic)
}
func (m *Sequence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sequence.Merge(m, src)
}
func (m *Sequence) XXX_Size() int {
	return xxx_messageInfo_Sequence.Size(m)
}
func (m *Sequence) XXX_DiscardUnknown() {
	xxx_messageInfo_Sequence.DiscardUnknown(m)
}

var xxx_messageInfo_Sequence proto.InternalMessageInfo

func (m *Sequence) GetType() SequenceType {
	if m != nil {
		return m.Type
	}
	return SequenceType_parallel
}

func (m *Sequence) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method               Methods  `protobuf:"varint,3,opt,name=method,proto3,enum=gol.Methods" json:"method,omitempty"`
	Body                 *any.Any `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Header               *any.Any `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Var                  []*Var   `protobuf:"bytes,6,rep,name=var,proto3" json:"var,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7052d12ff7cf86b, []int{3}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Job) GetMethod() Methods {
	if m != nil {
		return m.Method
	}
	return Methods_post
}

func (m *Job) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Job) GetHeader() *any.Any {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Job) GetVar() []*Var {
	if m != nil {
		return m.Var
	}
	return nil
}

type Var struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	JPath                string   `protobuf:"bytes,3,opt,name=jPath,proto3" json:"jPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Var) Reset()         { *m = Var{} }
func (m *Var) String() string { return proto.CompactTextString(m) }
func (*Var) ProtoMessage()    {}
func (*Var) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7052d12ff7cf86b, []int{4}
}

func (m *Var) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Var.Unmarshal(m, b)
}
func (m *Var) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Var.Marshal(b, m, deterministic)
}
func (m *Var) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Var.Merge(m, src)
}
func (m *Var) XXX_Size() int {
	return xxx_messageInfo_Var.Size(m)
}
func (m *Var) XXX_DiscardUnknown() {
	xxx_messageInfo_Var.DiscardUnknown(m)
}

var xxx_messageInfo_Var proto.InternalMessageInfo

func (m *Var) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Var) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Var) GetJPath() string {
	if m != nil {
		return m.JPath
	}
	return ""
}

func init() {
	proto.RegisterEnum("gol.Methods", Methods_name, Methods_value)
	proto.RegisterEnum("gol.SequenceType", SequenceType_name, SequenceType_value)
	proto.RegisterType((*ExecuteResponse)(nil), "gol.ExecuteResponse")
	proto.RegisterType((*ExecuteRequest)(nil), "gol.ExecuteRequest")
	proto.RegisterType((*Sequence)(nil), "gol.Sequence")
	proto.RegisterType((*Job)(nil), "gol.Job")
	proto.RegisterType((*Var)(nil), "gol.Var")
}

func init() {
	proto.RegisterFile("proto/gol.proto", fileDescriptor_d7052d12ff7cf86b)
}

var fileDescriptor_d7052d12ff7cf86b = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x9d, 0xc4, 0x99, 0x36, 0xfd, 0x53, 0xda, 0x8c, 0xe9, 0x22, 0x44, 0x2c, 0x46, 0x11, 0xa0,
	0x52, 0x41, 0x02, 0x65, 0x07, 0x2b, 0x84, 0x10, 0x52, 0x25, 0xc4, 0x28, 0xa0, 0x41, 0x62, 0x83,
	0x9c, 0xc4, 0x24, 0x41, 0x69, 0x6c, 0x6c, 0x67, 0xc0, 0x5b, 0xae, 0xc0, 0x89, 0x38, 0x03, 0x57,
	0xe0, 0x20, 0x28, 0x8e, 0x67, 0x34, 0xdd, 0xb0, 0x7b, 0xff, 0xfd, 0xe7, 0x6f, 0xbf, 0xe7, 0x0f,
	0x4b, 0x2e, 0x98, 0x62, 0x69, 0xc5, 0xda, 0xc4, 0x20, 0x8c, 0x2a, 0xd6, 0x46, 0x9f, 0xaa, 0x46,
	0xd5, 0x7d, 0x9e, 0x14, 0x6c, 0x9f, 0x56, 0x82, 0x17, 0x8f, 0x69, 0xc1, 0xa4, 0x96, 0x8a, 0xda,
	0xb2, 0x22, 0x8a, 0x7e, 0x27, 0x3a, 0x55, 0x75, 0x23, 0xca, 0xcf, 0x9c, 0x08, 0xa5, 0xd3, 0x8a,
	0xb1, 0xaa, 0xa5, 0x84, 0x37, 0xd2, 0xc2, 0x94, 0xf0, 0x26, 0x25, 0x5d, 0xc7, 0x14, 0x51, 0x0d,
	0xeb, 0xe4, 0x78, 0x41, 0x74, 0xc7, 0x76, 0x4d, 0x95, 0xf7, 0x5f, 0x52, 0xd2, 0xe9, 0xb1, 0x15,
	0x9f, 0xc2, 0xf2, 0xf5, 0x0f, 0x5a, 0xf4, 0x8a, 0x66, 0x54, 0x72, 0xd6, 0x49, 0x1a, 0xbf, 0x80,
	0xc5, 0x35, 0xf5, 0xad, 0xa7, 0x52, 0xe1, 0x87, 0xe0, 0xcb, 0x01, 0x76, 0x05, 0x0d, 0x9d, 0x33,
	0xb4, 0x3e, 0xd9, 0xde, 0x4a, 0x86, 0xe7, 0xbf, 0xb7, 0x64, 0x76, 0xdd, 0x8e, 0xdf, 0x81, 0x7f,
	0xc5, 0xe2, 0xfb, 0xe0, 0x29, 0xcd, 0x87, 0x23, 0xce, 0x7a, 0xb1, 0x3d, 0x3d, 0x38, 0xf2, 0x41,
	0x73, 0x9a, 0x99, 0x36, 0xbe, 0x0b, 0xde, 0x8e, 0xe5, 0x32, 0x74, 0xcd, 0x64, 0xdf, 0xc8, 0x76,
	0x2c, 0xcf, 0x0c, 0x1b, 0xff, 0x76, 0x00, 0xed, 0x58, 0x8e, 0x17, 0xe0, 0x36, 0xa5, 0x19, 0x35,
	0xcb, 0xdc, 0xa6, 0xc4, 0x01, 0xa0, 0x5e, 0xb4, 0xa1, 0x6b, 0x88, 0x01, 0xe2, 0x7b, 0x30, 0xd9,
	0x53, 0x55, 0xb3, 0x32, 0x44, 0xe6, 0xc2, 0xb9, 0x99, 0xf4, 0xd6, 0x50, 0x32, 0xb3, 0x3d, 0xbc,
	0x06, 0x2f, 0x67, 0xa5, 0x0e, 0xbd, 0x33, 0x67, 0x7d, 0xb2, 0x5d, 0x25, 0x63, 0x34, 0xc9, 0x55,
	0x34, 0xc9, 0xcb, 0x4e, 0x67, 0x46, 0x81, 0x1f, 0xc1, 0xa4, 0xa6, 0xa4, 0xa4, 0x22, 0x3c, 0xfe,
	0x8f, 0xd6, 0x6a, 0x70, 0x04, 0xe8, 0x92, 0x88, 0x70, 0x72, 0xc3, 0xc4, 0x05, 0x11, 0xd9, 0x40,
	0xc6, 0xaf, 0x00, 0x5d, 0x10, 0x81, 0x31, 0x78, 0x1d, 0xd9, 0x53, 0x6b, 0xc2, 0xe0, 0x81, 0x33,
	0x19, 0x8d, 0x3e, 0xc6, 0x40, 0x56, 0x70, 0xfc, 0xf5, 0x9c, 0xa8, 0xda, 0xf8, 0x98, 0x65, 0x63,
	0xb1, 0x79, 0x02, 0x53, 0xeb, 0x05, 0xfb, 0xe0, 0x71, 0x26, 0x55, 0x70, 0x84, 0xa7, 0x80, 0x2a,
	0xaa, 0x02, 0x67, 0x00, 0xbc, 0x57, 0x81, 0x8b, 0x67, 0x70, 0xcc, 0x89, 0x2a, 0xea, 0x00, 0x6d,
	0x1e, 0xc0, 0xfc, 0x66, 0xdc, 0x78, 0x0e, 0x3e, 0x27, 0x82, 0xb4, 0x2d, 0x6d, 0x83, 0xa3, 0x61,
	0x88, 0xd4, 0x5d, 0x11, 0x38, 0xdb, 0x8f, 0x80, 0xde, 0xb0, 0x16, 0x9f, 0xc3, 0xd4, 0xfe, 0x3b,
	0xbe, 0x6d, 0xde, 0x7f, 0xb8, 0x05, 0xd1, 0xea, 0x90, 0xb4, 0xdb, 0x12, 0xfd, 0xfc, 0xf3, 0xf7,
	0x97, 0xbb, 0x8a, 0x97, 0x66, 0xf7, 0x2e, 0x9f, 0xa6, 0x74, 0x14, 0x3c, 0x77, 0x36, 0xf9, 0xc4,
	0x24, 0xf5, 0xec, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x28, 0xe0, 0x90, 0xf2, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GolClient is the client API for Gol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GolClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type golClient struct {
	cc grpc.ClientConnInterface
}

func NewGolClient(cc grpc.ClientConnInterface) GolClient {
	return &golClient{cc}
}

func (c *golClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/gol.Gol/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GolServer is the server API for Gol service.
type GolServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

// UnimplementedGolServer can be embedded to have forward compatible implementations.
type UnimplementedGolServer struct {
}

func (*UnimplementedGolServer) Execute(ctx context.Context, req *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

func RegisterGolServer(s *grpc.Server, srv GolServer) {
	s.RegisterService(&_Gol_serviceDesc, srv)
}

func _Gol_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gol.Gol/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gol_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gol.Gol",
	HandlerType: (*GolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Gol_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gol.proto",
}
